# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], max_length=3)),
                ('Loan', models.IntegerField(validators=[loans.models.validate_loan])),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, validators=[loans.models.validate_name])),
                ('Body', models.CharField(max_length=5242880, validators=[loans.models.validate_body])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, validators=[loans.models.validate_name])),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.User', validators=[loans.models.validate_author]),
        ),
        migrations.AddField(
            model_name='report',
            name='Loans',
            field=models.ManyToManyField(to='loans.Loan'),
        ),
    ]
